import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/header";
import Footer from "@/components/footer";

const myFont = localFont({
  src: "./evolventa-bold.ttf",
});

console.log(myFont)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        <Header></Header>

        {children}

        <Footer></Footer>
      </body>
    </html>
  );
}
